### ISSUE TITLE
Fatal Error on zero results

### ISSUE THREAD

**Issue by lordsyncrus** [cookieguru/google-music-search#3]
Hi Cookieguru,
Thanks for this excellent work.

I'm not a brilliant programmer but i get a fatal error when zero results.

This is the error:
"Call to a member function getElementsByTagName() on null in .../google-music-search/API.php on line 92
"

I've coded a simply solution to prevent and die when $finder->query("//*[contains(@class,'card-list')]")->item(0) is NULL.

Hope this could be appreciated.

Cheers.

**Comment by cookieguru** [comment]
What is the search query you are using to get the fatal error?

**Comment by lordsyncrus** [comment]
Hi! :)

Try with this: Senti Antonio Molinini

2017-07-21 17:23 GMT+02:00 Tim Bond <notifications@github.com>:

**Comment by cookieguru** [comment]
I'm not able to reproduce the error.  I have a theory as to what's causing it; can you try updating to 1.0.3 and let me know?

---
Explanation:
The initial request goes to Google Play, and if the response contains `We couldn't find anything for your search` then no further processing is done.  My theory is that your server is in a country where English is not the predominant language, and Google's localization services detect this and serve up HTML in a different language.  I changed this 

If you dump out the HTML on [API.php:50](https://github.com/cookieguru/google-music-search/blob/master/API.php#L50), do you see `<div class="empty-search">` followed by a localized message informing you of zero search results?

Lastly, if you open [the same URL](https://play.google.com/store/search?c=music&q=Senti+Antonio+Molinini) in a browser, do you see a message of no results, or are there songs listed?

**Comment by lordsyncrus** [comment]
Hi Tim!

You are right!
I get the zero results message in Italian! (attached the $html var_dump).

Since I've updated to your last build everything works fine :)

Thank you so much!

Keep up the good job.

Greetings from Italy.



2017-07-21 22:27 GMT+02:00 Tim Bond <notifications@github.com>:
