### ISSUE TITLE
Class 'cookieguru\googlemusicsearch\API' not found

### ISSUE THREAD

**Issue by stanojeviclive** [cookieguru/google-music-search#4]
Hi,
I have error:
 Fatal error: Class 'cookieguru\googlemusicsearch\API' not found in index.php on line 3
Can U please help me.

Best regards,
Dejan

**Comment by cookieguru** [comment]
Did you run `composer require cookieguru/googlemusicsearch`?

**Comment by stanojeviclive** [comment]
not, i did with: `php composer.phar install`.
`composer require cookieguru/googlemusicsearch` works perfectly!
thank u
